trigger:
- dab_tamplate_wo_tf

parameters:
- name: is_run_after_deploy
  displayName: 'Run Job After Deployment'
  type: string
  default: 'false'
  values:
  - 'true'
  - 'false'
- name: job_name
  displayName: 'Job Name to Run'
  type: string
  default: 'dab_table_select_job'
- name: working_directory
  displayName: 'Working Directory'
  type: string
  default: '$(System.DefaultWorkingDirectory)/dab_sample'
- name: target
  displayName: 'DAB Job Target'
  type: string
  default: 'dev'

pool:
  name: dbxbcpool

variables:
  - group: scb-demo    # Reference to the variable group



steps:
# Step 0: Install az command
- task: Bash@3
  displayName: 'Install az command'
  inputs:
    targetType: 'inline'
    script: |
      curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

# Step 0.25: Install Required Packages
- task: Bash@3
  displayName: 'Install Required Packages'
  inputs:
    targetType: 'inline'
    script: |
      echo "Installing required packages..."
      sudo apt-get update
      sudo apt-get install -y unzip curl wget ca-certificates
      echo "Required packages installed successfully."

# Step 0.5: Install Databricks CLI
- task: Bash@3
  displayName: 'Install Databricks CLI'
  inputs:
    targetType: 'inline'
    script: |
      echo "Installing Databricks CLI..."
      curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sudo sh
      echo 'export PATH="/home/vsts/.local/bin:$PATH"' >> ~/.bashrc
      source ~/.bashrc
      databricks --version

# Step 1: Login to Azure
- task: Bash@3
  displayName: 'Login to Azure'
  inputs:
    targetType: 'inline'
    script: |
      set -e  # Exit on any error
      echo "Logging in to Azure interactively..."
      az login --service-principal --username $(azure_sp_client_id) --password $(azure_sp_client_secret) --tenant $(azure_sp_tenant_id)
      if [ $? -ne 0 ]; then
        echo "ERROR: Azure login failed"
        exit 1
      fi
      # az login --use-device-code # interactive login
      az account set --subscription $(subscription_id)
      if [ $? -ne 0 ]; then
        echo "ERROR: Failed to set subscription"
        exit 1
      fi
      echo "Azure login successful"

# Step 2: Validate Databricks Asset Bundle
- task: Bash@3
  displayName: 'Validate Databricks Asset Bundle'
  inputs:
    targetType: 'inline'
    workingDirectory: '${{ parameters.working_directory }}'
    script: |
      set -e  # Exit on any error
      echo "Validating Databricks Asset Bundle..."
      databricks bundle validate -t # ${{ parameters.target }}
      if [ $? -ne 0 ]; then
        echo "ERROR: Bundle validation failed"
        exit 1
      fi
      echo "Bundle validation completed successfully."

# Step 3: Deploy Databricks Asset Bundle
- task: Bash@3
  displayName: 'Deploy Databricks Asset Bundle'
  inputs:
    targetType: 'inline'
    workingDirectory: '${{ parameters.working_directory }}'
    script: |
      set -e  # Exit on any error
      echo "Deploying Databricks Asset Bundle..."
      databricks bundle deploy -t ${{ parameters.target }}
      if [ $? -ne 0 ]; then
        echo "ERROR: Bundle deployment failed"
        exit 1
      fi
      echo "Bundle deployment completed successfully."

# Step 4: Run Databricks Job (Conditional)
- task: Bash@3
  displayName: 'Run Databricks Job'
  condition: and(succeeded(), eq('${{ parameters.is_run_after_deploy }}', 'true'))
  inputs:
    targetType: 'inline'
    workingDirectory: '${{ parameters.working_directory }}'
    script: |
      set -e  # Exit on any error
      echo "Running Databricks job after deployment..."
      if [ -n "${{ parameters.job_name }}" ]; then
        databricks bundle run ${{ parameters.job_name }} -t ${{ parameters.target }} --no-wait
        if [ $? -ne 0 ]; then
          echo "ERROR: Job execution failed"
          exit 1
        fi
        echo "Job execution initiated successfully."
      else
        echo "No job name specified, skipping job execution."
      fi